title: k-Means Clustering Analysis - COVID-19 Infection Rate, Digital Propensity and Access to Amenities
logo: /Images/Clusters_map.jpg
description: Overiew of analysis and findings
theme: jekyll-theme-minimal
