title: DS Portfolio
logo: /Images/cp_profile_pic.jpg
description: I help vulnerable residents of Barnsley improve life outcomes and access better services by solving complex challenges around efficiency and service delivery, by combining lived experience, systems thinking, and a ground up, resident centred approach, with a focus on transparency, simplicity, and ethics. I'm currently building expertise in AI, automation, and data engineering for agentic AI to help local authorities deliver better, more responsive public services.
show_downloads: true
theme: jekyll-theme-minimal
