title: Data Science Professional Portfolio
logo: /Images/cp_profile_pic.jpg
description: k-Means Clustering Analysis - COVID-19 Infection Rate, Digital Propensity and Access to Amenities
theme: jekyll-theme-minimal
